name             'httpd_undo'
maintainer       'Mrchowdary'
maintainer_email 'learnchef@chef.io'
license          'Apache 2.0'
description      'UnInstalls configured package httpd.'
long_description 'UnInstalls and configures package httpd and sets a basic home page. This cookbook is used by the Learn Chef tutorials. https://learn.chef.io'
supports         'centos'
supports         'redhat'
version          '0.2.0'
